[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools>=60", "setuptools_scm[toml]>=8.0"]

[project]
authors = [
  { name = "Ken Lauer", email = "152229072+ken-lauer@users.noreply.github.com" },
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Natural Language :: English",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Topic :: Scientific/Engineering",
]
dependencies = []
description = "A formatter and round-trip parser for Fortran namelists"
dynamic = ["version"]
keywords = []
name = "nmlform"
readme = { file = "README.md", content-type = "text/markdown" }
requires-python = ">=3.10"

[project.urls]
Homepage = "https://github.com/ken-lauer/nmlform"
Repository = "https://github.com/ken-lauer/nmlform"
Issues = "https://github.com/ken-lauer/nmlform/issues"
Documentation = "https://ken-lauer.github.io/nmlform"

[project.optional-dependencies]
all = ["pyyaml", "tomli; python_version < '3.11'"]
test = ["pytest", "pytest-cov", "pyyaml", "tomli; python_version < '3.11'"]
doc = [
  "mkdocs",
  "mkdocs-jupyter",
  "mkdocs-macros-plugin",
  "mkdocs-material",
  "mkdocstrings",
  "mkdocstrings-python",
]

[tool.setuptools.packages.find]
where = ["src"]
namespaces = false

[project.license]
file = "LICENSE"

[project.scripts]
"nmlform" = "nmlform.main:cli_main"
"nmlform-set" = "nmlform.apply:cli_main_set"

[tool.ruff]
# Reference and defaults: https://docs.astral.sh/ruff/configuration/
# exclude = []
line-length = 100
indent-width = 4
target-version = "py310"

[tool.ruff.lint]
select = [
  # Pycodestyle E errors: https://pycodestyle.pycqa.org/en/latest/intro.html
  "E4",
  "E7",
  "E9",
  # pyflakes F error codes:
  # https://flake8.pycqa.org/en/latest/user/error-codes.html
  "F",
  # isort: import sorting
  "I",
  # pyupgrade: modernize syntax
  "UP",
  # ruff-specific rules
  "RUF",
]
ignore = [
  # Ignore ambiguous variables such as `I`
  "E741",
]

[tool.pytest.ini_options]
addopts = "--cov=src/"
log_cli_level = "INFO"
log_level = "DEBUG"
testpaths = ["src/nmlform/tests"]
# Early warning system for deprecations - consider uncommenting this block:
# filterwarnings = [
#   "error::DeprecationWarning",
#   "error::PendingDeprecationWarning",
# ]

[tool.setuptools_scm]
version_file = "src/nmlform/_version.py"
fallback_version = "0.0.0.dev0"
# For publishing to testpypi (no funny local dev+hash suffix)
local_scheme = "no-local-version"
