!------------------------------------------------------------------------
&tao_start
  plot_file = 'tao_plot.init'   ! trailing comment after a value
  startup_file = 'tao.startup'
/

&tao_design_lattice
  n_universes = 4
!  unique_name_suffix="*::_##?"
!design_lattice(1)%file = "old.lat.bmad"
  design_lattice(1)%file='$PROJ/a.lat.bmad'
  design_lattice(2)%file='b.lat.bmad'
  design_lattice(3)%file='sub/c.lat.bmad'
  design_lattice(4)%file='sub/d.lat.bmad'
/

&tao_params
  global%random_engine = 'pseudo' ! or: 'quasi'
  bmad_com%radiation_damping_on = F
  /

!&tao_d2_data
        d2_data%name = "commented_out"
        universe = 1
        n_d1_data = 1
/

&tao_var
	v1_var%name = 'quad'
	default_key_bound = T
/
